spring.application.name=NexU

# Mail settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_SMPT_USERNAME}
spring.mail.password=${MAIL_SMPT_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Datasource settings
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#docker run -p 5557:5432 --name nexu -e POSTGRES_DB=nexu_db -e POSTGRES_PASSWORD=123 -d postgres;

server.forward-headers-strategy=native
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto

# JWT settings
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=DEBUG
my.awesome.secret=${JWT_SECRET}

# AWS settings
amazonS3.accessKey=${aws_access_key_id}
amazonS3.secretKey=${aws_secret_access_key}
amazonS3.sessionToken=${aws_session_token}
amazonS3.region=${REGION_AWS}
amazonS3.bucketName=${BUCKET_NAME}

# Google Maps api
google.maps.api.key=${MAPS_KEY}
